# Generated by Django 5.2.6 on 2025-12-17 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_level"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="level",
            options={"managed": False},
        ),
    ]
