# Generated by Django 5.2.9 on 2026-01-06 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_category_options_alter_level_options"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="category",
            table="category",
        ),
        migrations.AlterModelTable(
            name="level",
            table="level",
        ),
    ]
