name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  frontend:
    name: "Frontend CI"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Security audit
        run: npm audit --audit-level=moderate
      - name: Run linter
        run: npm run lint
      - name: Type check
        run: npx tsc --noEmit
      - name: Build application
        run: npm run build
        env:
          NODE_ENV: production

  backend:
    name: "Backend CI"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: back-django
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Install pip-audit
        run: pip install pip-audit
      - name: Security audit
        run: pip-audit

      - name: Lint code with pylint
        run: pylint .
      - name: Check code format with black
        run: black --check .
      - name: Check import sorting with isort
        run: isort . --check-only
      - name: Run Django tests
        run: python manage.py test
      - name: Build application
        run: echo "No build step needed"
