name: Cron Job
on:
  schedule:
    #- cron: 0 3 */3 * *
    - cron: "*/5 * * * *"
jobs:
  run-every-three-days:
    runs-on: ubuntu-latest
    steps:
      - name: Afficher un message
        run: echo "Ce job s'exécute tous les trois jours !"
      - name: Afficher la date et l'heure actuelles
        run: date
